services:
  pgmover-15:
    build:
      context: .
      dockerfile: Dockerfile.15
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}-15:latest
          - ghcr.io/${GITHUB_REPOSITORY}-15:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64

  pgmover-16:
    build:
      context: .
      dockerfile: Dockerfile.16
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}-16:latest
          - ghcr.io/${GITHUB_REPOSITORY}-16:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
